---
- hosts: zabbixClients
  become: yes
  tasks:
    - name: Backup zabbix-agent.conf
      copy:
        src: /etc/zabbix/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf.back
        remote_src: yes

    - name: remove zabbix-agent-4.4.10
      yum:
        name: zabbix-agent
        state: removed
    
    - name: Install zabbix-agent-5.0.8
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-agent-5.0.8-1.el7.x86_64.rpm
        state: present

    - name: Configure zabbix-agent
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        replace: Server=192.168.110.144

    - name: Enable and start Zabbix agent service
      systemd:
        daemon_reload: yes
        name: zabbix-agent
        enabled: yes
        state: started

